# Site settings
title: SMS-Activate.app
email: contact@sms-activate.app
author: SMS-Activate
description: "Secure and private virtual phone numbers for SMS verification on any service. Activate online services without revealing your real phone number."
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://sms-activate.app" # the base hostname & protocol for your site
twitter_username: PrivatePhoneBot
github_username: VirtualPhoneNumber
telegram_username: PrivatePhoneBot
google_analytics: G-VNJRLSL3WX # Replace with your actual Tracking ID

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from build
exclude:
  - node_modules/
  - package.json
  - package-lock.json

# SEO Tags
seo:
  type: WebPage
  image:
    path: /assets/images/share-image.jpg
    height: 630
    width: 1200
  twitter:
    card: summary_large_image
    site: "{{ site.twitter_username }}"
    creator: "{{ site.twitter_username }}"

# Social links
social_links:
  twitter: https://twitter.com/PrivatePhoneBot
  telegram: https://t.me/PrivatePhoneBot
  github: https://github.com/VirtualPhoneNumber

# Footer settings
footer:
  copyright: "Copyright © {{ 'now' | date: '%Y' }} SMS-Activate.app. All Rights Reserved."

# Default configuration for languages
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
      layout: "default"
  - scope:
      path: "ru"
    values:
      lang: "ru"
      layout: "default"
  - scope:
      path: "zh"
    values:
      lang: "zh"
      layout: "default"

# Navigation settings for English
navigation_en:
  - title: "Home"
    url: "/"
  - title: "Services"
    url: "/services"
    submenu:
      - title: "Services"
        url: "/services"
      - title: "SMS Verification"
        url: "/sms-verification"
      - title: "Virtual Phone Numbers"
        url: "/virtual-phone-numbers"
      - title: "Temporary Phone Numbers"
        url: "/temporary-phone-numbers"
      - title: "Elite Phone Numbers"
        url: "/elite-phone-numbers"
      - title: "Free Phone Numbers"
        url: "/free-phone-numbers"
      - title: "Phone Number Generator"
        url: "/phone-number-generator"
  - title: "FAQ"
    url: "/faq"
    submenu:
      - title: "FAQ"
        url: "/faq"
      - title: "How It Works"
        url: "/how-it-works"
      - title: "Pricing"
        url: "/pricing"
  - title: "API"
    url: "/api"
    submenu:
      - title: "API"
        url: "/api"
      - title: "API Documentation"
        url: "/api-documentation"
      - title: "Webhook"
        url: "/webhook"
      - title: "Redirect"
        url: "/redirect"
  - title: "Contact"
    url: "/contact"
    submenu:
      - title: "Contact"
        url: "/contact"
      - title: "Support"
        url: "/support"
      - title: "About Us"
        url: "/about-us"
      - title: "Privacy Policy"
        url: "/privacy-policy"
      - title: "Terms of Service"
        url: "/terms-of-service"
  - title: "For Partners"
    url: "/for-partners"
    submenu:
      - title: "For Partners"
        url: "/for-partners"
      - title: "Affiliate Program"
        url: "/affiliate-program"
      - title: "Reseller Program"
        url: "/reseller-program"
      - title: "Referral Program"
        url: "/referral-program"
  - title: "Blog"
    url: "/blog"
    submenu:
      - title: "Blog"
        url: "/blog"
      - title: "SMS Verification Binance"
        url: "/en/blog/sms-verification-binance"
      - title: "SMS Verification WhatsApp"
        url: "/en/blog/sms-verification-whatsapp"
      - title: "SMS Verification Revolut"
        url: "/en/blog/sms-verification-revolut"
      - title: "SMS Verification Wise"
        url: "/en/blog/sms-verification-wise"
      - title: "SMS Verification Telegram"
        url: "/en/blog/sms-verification-telegram"
      - title: "SMS Verification Amazon"
        url: "/en/blog/sms-verification-amazon"
      - title: "SMS Verification Google"
        url: "/en/blog/sms-verification-google"
      - title: "SMS Verification Apple"
        url: "/en/blog/sms-verification-apple"
      - title: "SMS Verification Tinder"
        url: "/en/blog/sms-verification-tinder"
      - title: "SMS Verification PayPal"
        url: "/en/blog/sms-verification-paypal"
      - title: "SMS Verification Payoneer"
        url: "/en/blog/sms-verification-payoneer"
      - title: "SMS Verification OKX"
        url: "/en/blog/sms-verification-okx"
      - title: "SMS Verification ByBit"
        url: "/en/blog/sms-verification-bybit"
      - title: "SMS Verification KuCoin"
        url: "/en/blog/sms-verification-KuCoin"
      - title: "SMS Verification Banks"
        url: "/en/blog/sms-verification-banks"
      - title: "SMS Verification Social Networks"
        url: "/en/blog/sms-verification-social-networks"
      - title: "SMS Verification E-Commerce"
        url: "/en/blog/sms-verification-e-commerce"
      - title: "SMS Verification WhatsApp Business"
        url: "/en/blog/sms-verification-freelancers"
  - title: "Get Started"
    url: "/get-started"

  # Russian Navigation
navigation_ru:
  - title: "Главная"
    url: "/ru/"
  - title: "Услуги"
    url: "/ru/services"
    submenu:
      - title: "Услуги"
        url: "/ru/services"
      - title: "СМС Верификация"
        url: "/ru/sms-verification"
      - title: "Виртуальные Номера"
        url: "/ru/virtual-phone-numbers"
      - title: "Временные Номера"
        url: "/ru/temporary-phone-numbers"
      - title: "Элитные Номера"
        url: "/ru/elite-phone-numbers"
      - title: "Бесплатные Номера"
        url: "/ru/free-phone-numbers"
      - title: "Генератор Номеров"
        url: "/ru/phone-number-generator"
  - title: "Вопросы и Ответы"
    url: "/ru/faq"
    submenu:
      - title: "Вопросы и Ответы"
        url: "/ru/faq"
      - title: "Как это работает"
        url: "/ru/how-it-works"
      - title: "Цены"
        url: "/ru/pricing"
  - title: "API"
    url: "/ru/api"
    submenu:
      - title: "API"
        url: "/ru/api"
      - title: "Документация API"
        url: "/ru/api-documentation"
      - title: "Webhook"
        url: "/ru/webhook"
      - title: "Перенаправление"
        url: "/ru/redirect"
  - title: "Контакты"
    url: "/ru/contact"
    submenu:
      - title: "Контакты"
        url: "/ru/contact"
      - title: "Поддержка"
        url: "/ru/support"
      - title: "О нас"
        url: "/ru/about-us"
      - title: "Политика конфиденциальности"
        url: "/ru/privacy-policy"
      - title: "Условия обслуживания"
        url: "/ru/terms-of-service"
  - title: "Для Партнеров"
    url: "/ru/for-partners"
    submenu:
      - title: "Для Партнеров"
        url: "/ru/for-partners"
      - title: "Партнерская Программа"
        url: "/ru/affiliate-program"
      - title: "Программа для Перепродавцов"
        url: "/ru/reseller-program"
      - title: "Реферальная Программа"
        url: "/ru/referral-program"
  - title: "Блог"
    url: "/ru/blog"
    submenu:
      - title: "Блог"
        url: "/ru/blog"
      - title: "СМС Верификация Binance"
        url: "/ru/blog/sms-verification-binance"
      - title: "СМС Верификация WhatsApp"
        url: "/ru/blog/sms-verification-whatsapp"
      - title: "СМС Верификация Revolut"
        url: "/ru/blog/sms-verification-revolut"
      - title: "СМС Верификация Wise"
        url: "/ru/blog/sms-verification-wise"
      - title: "СМС Верификация Telegram"
        url: "/ru/blog/sms-verification-telegram"
      - title: "СМС Верификация Amazon"
        url: "/ru/blog/sms-verification-amazon"
      - title: "СМС Верификация Google"
        url: "/ru/blog/sms-verification-google"
      - title: "СМС Верификация Apple"
        url: "/ru/blog/sms-verification-apple"
      - title: "СМС Верификация Tinder"
        url: "/ru/blog/sms-verification-tinder"
      - title: "СМС Верификация PayPal"
        url: "/ru/blog/sms-verification-paypal"
      - title: "СМС Верификация Payoneer"
        url: "/ru/blog/sms-verification-payoneer"
      - title: "СМС Верификация OKX"
        url: "/ru/blog/sms-verification-okx"
      - title: "СМС Верификация ByBit"
        url: "/ru/blog/sms-verification-bybit"
      - title: "СМС Верификация KuCoin"
        url: "/ru/blog/sms-verification-KuCoin"
      - title: "СМС Верификация Банков"
        url: "/ru/blog/sms-verification-banks"
      - title: "СМС Верификация Социальных Сетей"
        url: "/ru/blog/sms-verification-social-networks"
      - title: "СМС Верификация для Интернет-Магазинов"
        url: "/ru/blog/sms-verification-e-commerce"
      - title: "СМС Верификация WhatsApp Business"
        url: "/ru/blog/sms-verification-freelancers"
  - title: "Начать"
    url: "/ru/get-started"

  # Navigation settings for Chinese
navigation_zh:
  - title: "首页"
    url: "/zh/"
  - title: "服务"
    url: "/zh/services"
    submenu:
      - title: "服务"
        url: "/zh/services"
      - title: "短信验证"
        url: "/zh/sms-verification"
      - title: "虚拟号码"
        url: "/zh/virtual-phone-numbers"
      - title: "临时号码"
        url: "/zh/temporary-phone-numbers"
      - title: "精英号码"
        url: "/zh/elite-phone-numbers"
      - title: "免费号码"
        url: "/zh/free-phone-numbers"
      - title: "号码生成器"
        url: "/zh/phone-number-generator"
  - title: "常见问题解答"
    url: "/zh/faq"
    submenu:
      - title: "常见问题解答"
        url: "/zh/faq"
      - title: "如何使用"
        url: "/zh/how-it-works"
      - title: "价格"
        url: "/zh/pricing"
  - title: "API"
    url: "/zh/api"
    submenu:
      - title: "API"
        url: "/zh/api"
      - title: "API 文档"
        url: "/zh/api-documentation"
      - title: "Webhook"
        url: "/zh/webhook"
      - title: "重定向"
        url: "/zh/redirect"
  - title: "联系方式"
    url: "/zh/contact"
    submenu:
      - title: "联系方式"
        url: "/zh/contact"
      - title: "支持"
        url: "/zh/support"
      - title: "关于我们"
        url: "/zh/about-us"
      - title: "隐私政策"
        url: "/zh/privacy-policy"
      - title: "服务条款"
        url: "/zh/terms-of-service"
  - title: "合作伙伴"
    url: "/zh/for-partners"
    submenu:
      - title: "合作伙伴"
        url: "/zh/for-partners"
      - title: "合作伙伴计划"
        url: "/zh/affiliate-program"
      - title: "经销商计划"
        url: "/zh/reseller-program"
      - title: "推荐计划"
        url: "/zh/referral-program"
  - title: "博客"
    url: "/zh/blog"
    submenu:
      - title: "博客"
        url: "/zh/blog"
      - title: "Binance 短信验证"
        url: "/zh/blog/sms-verification-binance"
      - title: "WhatsApp 短信验证"
        url: "/zh/blog/sms-verification-whatsapp"
      - title: "Revolut 短信验证"
        url: "/zh/blog/sms-verification-revolut"
      - title: "Wise 短信验证"
        url: "/zh/blog/sms-verification-wise"
      - title: "Telegram 短信验证"
        url: "/zh/blog/sms-verification-telegram"
      - title: "Amazon 短信验证"
        url: "/zh/blog/sms-verification-amazon"
      - title: "Google 短信验证"
        url: "/zh/blog/sms-verification-google"
      - title: "Apple 短信验证"
        url: "/zh/blog/sms-verification-apple"
      - title: "Tinder 短信验证"
        url: "/zh/blog/sms-verification-tinder"
      - title: "PayPal 短信验证"
        url: "/zh/blog/sms-verification-paypal"
      - title: "Payoneer 短信验证"
        url: "/zh/blog/sms-verification-payoneer"
      - title: "OKX 短信验证"
        url: "/zh/blog/sms-verification-okx"
      - title: "ByBit 短信验证"
        url: "/zh/blog/sms-verification-bybit"
      - title: "KuCoin 短信验证"
        url: "/zh/blog/sms-verification-KuCoin"
      - title: "银行短信验证"
        url: "/zh/blog/sms-verification-banks"
      - title: "社交网络短信验证"
        url: "/zh/blog/sms-verification-social-networks"
      - title: "电子商务短信验证"
        url: "/zh/blog/sms-verification-e-commerce"
      - title: "WhatsApp Business 短信验证"
        url: "/zh/blog/sms-verification-freelancers"
  - title: "开始"
    url: "/zh/get-started"
